################################################################################
# docker-compose.yml
#
# Media services.
#
################################################################################

sabnzbd:
  image: timhaak/sabnzbd
  ports:
  - "8080:8080"
  - "9090:9090"
  volumes:
  - "./volumes/config/sabnzbd:/config"
  - "./volumes/data:/data"
  - "./volumes/scratch:/scratch"

couchpotato:
  image: timhaak/couchpotato
  ports:
  - "5050:5050"
  links:
  - sabnzbd
  volumes:
  - "./volumes/config/couchpotato:/config"
  - "./volumes/data:/mnt/data"
  - "./volumes/scratch:/mnt/scratch"

sickrage:
  image: timhaak/sickrage
  ports:
  - "8081:8081"
  links:
  - sabnzbd
  volumes:
  - "./volumes/config/sickrage:/config"
  - "./volumes/data:/data"
  - "./volumes/scratch:/scratch"

plex_config:
  image: busybox
  volumes:
  - /config

plex:
  image: linuxserver/plex
  net: "host"
  ports:
    - "32400:32400"
  volumes:
    #- "./volumes/config/plex:/config"
    - "./volumes/data/Movies:/mnt/Movies"
    - "./volumes/data/TV:/mnt/TV"
  volumes_from:
    - plex_config
