################################################################################
# docker-compose.yml
#
# Media services.
#
################################################################################
version: '2'

volumes:
  # Encountered permissions issues with Plex volumes, but this one will work.
  # This volume will persist over compose stop/starts but will be lost on
  # Docker Machine removal!
  plex_config:
    driver: local

services:
  sabnzbd:
    image: timhaak/sabnzbd
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./volumes/config/sabnzbd:/config
      - ./volumes/data:/data
      - ./volumes/scratch:/scratch

  couchpotato:
    image: timhaak/couchpotato
    ports:
      - 5050:5050
    links:
      - sabnzbd
    volumes:
      - ./volumes/config/couchpotato:/config
      - ./volumes/data:/mnt/data
      - ./volumes/scratch:/mnt/scratch

  sickrage:
    image: timhaak/sickrage
    ports:
      - 8081:8081
    links:
      - sabnzbd
    volumes:
      - ./volumes/config/sickrage:/config
      - ./volumes/data:/data
      - ./volumes/scratch:/scratch

  plex:
    image: linuxserver/plex
    network_mode: host
    volumes:
      - plex_config:/config
      - ./volumes/data/Movies:/mnt/Movies
      - ./volumes/data/TV:/mnt/TV
